### PR TITLE
Fix test

### PR DESCRIPTION
**Pull request by diegoferigo**
My CI pipeline is failing due to this, likely after https://github.com/robotology/idyntree/pull/751.

```
/usr/bin/c++  -isystem /iit/local/include -O2 -g -DNDEBUG -MD -MT tests/CMakeFiles/icub-model-test.dir/icub-model-test.cpp.o -MF tests/CMakeFiles/icub-model-test.dir/icub-model-test.cpp.o.d -o tests/CMakeFiles/icub-model-test.dir/icub-model-test.cpp.o -c ../tests/icub-model-test.cpp
../tests/icub-model-test.cpp:5:10: fatal error: iDynTree/Model/Indeces.h: No such file or directory
    5 | #include <iDynTree/Model/Indeces.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

See https://github.com/diegoferigo/development-iit/runs/1375093377?check_suite_focus=true#step:3:27903

### CODE REVIEW

**Review by traversaro — APPROVED** [review]

**Comment by traversaro** [comment]
Thanks!
